name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{secrets.DOCKERHUB_USERNAME}}
      #     password: ${{secrets.DOCKERHUB_PASSWORD}}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./location-app
      #     file: ./location-app/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: iamwaseem/test-app:latest
      # Finally.
      - 
        name: curl
        run: |
          curl --location --request POST 'http://3.14.85.185:8002/fs/post_kafka' \
          --header 'Content-Type: application/json' \
          --data-raw '{"version": "120"}'