name: test
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo "Released version is : ${{ steps.vars.outputs.tag }}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./location-app
          file: ./location-app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "iamwaseem/steward-test:${{ steps.vars.outputs.tag }}"


#       - name: Check output
#         env:
#           RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#         run: |
#           echo $RELEASE_VERSION
#           echo ${{ steps.vars.outputs.tag }}
# name: ci

# on:
#   push:
#     branches:
#       - 'main'
#     tags:
#       - 'v*.*.*'

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
        
#       -
#         name: Docker meta
#         id: meta
#         uses: docker/metadata-action@v3
#         with:
#           # list of Docker images to use as base name for tags
#           images: |
#             i-am-waseem/steward-test
#           # generate Docker tags based on the following events/attributes
#           tags: |
#             type=schedule
#             type=ref,event=branch
#             type=ref,event=pr
#             type=semver,pattern={{version}}
#             type=semver,pattern={{major}}.{{minor}}
#             type=semver,pattern={{major}}
#             type=sha
#       - name: Echoing the output
#         run: |
#           echo "Tags: "
#           echo "${{ steps.meta.outputs.tags }}"
#           echo "Labels: "
#           echo "${{ steps.meta.outputs.labels }}"
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{secrets.DOCKERHUB_USERNAME}}
#           password: ${{secrets.DOCKERHUB_PASSWORD}}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./location-app
#           file: ./location-app/Dockerfile
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
      # Finally. Not done yet.
      - 
        name: curl
        run: |
          curl --location --request POST 'http://18.221.148.219:3000/fs/post_kafka' \
          --header 'Content-Type: application/json' \
          --data-raw '{"version": "10"}'
